version: '3.7'
services:
  postgresql:
    image: postgres:15-alpine
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: on-failure
    ports:
      - "5432:5432"
  bot:
    build: .
    command: sh -c "make migrate && python bot"
    env_file:
      - .env
    restart: always
    depends_on:
      - postgresql
volumes:
  pgdata:
